FROM tiangolo/uvicorn-gunicorn:python3.8-slim

WORKDIR /code
COPY .env /code

COPY ./requirements.txt /code/requirements.txt

RUN apt-get update && apt-get install -y netcat
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./core /code/core

RUN pip install -r requirements.txt

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker",   "core.main:app", "-b", ":8000"]
